version: "3.5"
networks:
  charter-local:
    driver: bridge
services:
  postgres_charter:
    container_name: postgres_charter
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "charter"
    image: postgres:12.13-alpine
    ports:
      - '5439:5432'
    networks:
      charter-local:
        aliases:
          - postgres
    volumes:
      - ./data:/var/lib/postgresql/data
